export const usersData = [
  {
    id: 1,
    userName: 'Segunade@retail',
    name: 'segun',
    role: 'Cashier',
    email: 'Segunade@retail.com',
  },
  {
    id: 2,
    userName: 'Segunade@retail',
    name: 'Olakunbi',
    role: 'Cashier',
    email: 'Segunade@retail.com',
  },
  {
    id: 3,
    userName: 'Segunade@retail',
    name: 'segun',
    role: 'Cashier',
    email: 'Segunade@retail.com',
  },
  {
    id: 4,
    userName: 'Segunade@retail',
    name: 'segun',
    role: 'Cashier',
    email: 'Segunade@retail.com',
  },
  {
    id: 5,
    userName: 'Segunade@retail',
    name: 'segun',
    role: 'Manager',
    email: 'Segunade@retail.com',
  },
  {
    id: 6,
    userName: 'Segunade@retail',
    name: 'segun',
    role: 'Cashier',
    email: 'Segunade@retail.com',
  },
  {
    id: 7,
    userName: 'Segunade@retail',
    name: 'segun',
    role: 'Cashier',
    email: 'Segunade@retail.com',
  },
];
