export const products = [
    {
        id: 1,
        name: 'Amstel Malta (Malt drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 2,
        name: 'Ariel (Laundry detergent)',
        price: 400,
        unit: "Pieces",
    },
    {
        id: 3,
        name: 'Closeup (Toothpaste)',
        price: 1200,
        unit: "Pieces",
    },
    {
        id: 4,
        name: 'Milo (Chocolate drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 5,
        name: 'Dangote (Flour)',
        price: 1000,
        unit: "Pieces",
    },
    {
        id: 6,
        name: 'Knorr (Seasoning Cubes)',
        price: 400,
        unit: "Pieces",
    },
    {
        id: 7,
        name: 'Morning Fresh(Dishwashing Liquid)',
        price: 600,
        unit: "Pieces",
    },
    {
        id: 8,
        name: 'Closeup (Toothpaste)',
        price: 1200,
        unit: "Pieces",
    },
    {
        id: 9,
        name: 'Milo (Chocolate drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 10,
        name: 'Dangote (Flour)',
        price: 1000,
        unit: "Pieces",
    },
    {
        id: 11,
        name: 'Amstel Malta (Malt drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 12,
        name: 'Ariel (Laundry detergent)',
        price: 400,
        unit: "Pieces",
    },
    {
        id: 13,
        name: 'Closeup (Toothpaste)',
        price: 1200,
        unit: "Pieces",
    },
    {
        id: 14,
        name: 'Milo (Chocolate drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 15,
        name: 'Dangote (Flour)',
        price: 1000,
        unit: "Pieces",
    },
    {
        id: 16,
        name: 'Amstel Malta (Malt drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 17,
        name: 'Ariel (Laundry detergent)',
        price: 400,
        unit: "Pieces",
    },
    {
        id: 18,
        name: 'Closeup (Toothpaste)',
        price: 1200,
        unit: "Pieces",
    },
    {
        id: 19,
        name: 'Milo (Chocolate drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 20,
        name: 'Dangote (Flour)',
        price: 1000,
        unit: "Pieces",
    },
    {
        id: 21,
        name: 'Amstel Malta (Malt drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 22,
        name: 'Ariel (Laundry detergent)',
        price: 400,
        unit: "Pieces",
    },
    {
        id: 23,
        name: 'Closeup (Toothpaste)',
        price: 1200,
        unit: "Pieces",
    },
    {
        id: 24,
        name: 'Milo (Chocolate drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 25,
        name: 'Dangote (Flour)',
        price: 1000,
        unit: "Pieces",
    },
    {
        id: 26,
        name: 'Amstel Malta (Malt drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 27,
        name: 'Ariel (Laundry detergent)',
        price: 400,
        unit: "Pieces",
    },
    {
        id: 28,
        name: 'Closeup (Toothpaste)',
        price: 1200,
        unit: "Pieces",
    },
    {
        id: 29,
        name: 'Milo (Chocolate drink)',
        price: 200,
        unit: "Pieces",
    },
    {
        id: 30,
        name: 'Dangote (Flour)',
        price: 1000,
        unit: "Pieces",
    },
];